inherit_gem:
  relaxed-rubocop: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
