---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6.5
  - 2.7
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install: gem install bundler -v 2.0.1
