---
os: linux
language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
  - ruby-head
jobs:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install:
  - gem update --system
  - gem install bundler
  
